[project]
name = "hos-eld-trip-planner"
version = "0.1.0"
description = "HOS Compliant ELD Trip Planner"
authors = [
    {name = "XZANATOL", email = "abdelrahmanbedox@gmail.com"},
]
dependencies = ["django>=6.0.1", "djangorestframework>=3.16.1", "pytest>=9.0.2", "gunicorn>=24.1.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "python './hos_eld_trip_planner/manage.py' runserver"